import type { Wig } from './types';
import { placeholderImages } from './placeholder-images';

const getImage = (id: string) => placeholderImages.find(p => p.id === id)?.imageUrl || `https://picsum.photos/seed/${id}/600/800`;

export const products: Wig[] = [
  {
    id: 'w1',
    name: 'Golden Waves',
    price: 189.99,
    image: getImage('wig1'),
    description: 'Beautiful long, wavy blonde hair that flows naturally. Made from high-quality synthetic fibers.',
    style: 'Wavy',
    color: 'Blonde',
    length: 'Long',
    material: 'Synthetic',
  },
  {
    id: 'w2',
    name: 'Chic Brunette Bob',
    price: 220.50,
    image: getImage('wig2'),
    description: 'A timeless and chic bob cut in a rich brunette shade. Made from 100% human hair.',
    style: 'Bob',
    color: 'Brunette',
    length: 'Short',
    material: 'Human Hair',
  },
  {
    id: 'w3',
    name: 'Fiery Red Curls',
    price: 155.00,
    image: getImage('wig3'),
    description: 'Make a statement with these vibrant, bouncy red curls. Fun, fearless, and fabulous.',
    style: 'Curly',
    color: 'Red',
    length: 'Medium',
    material: 'Synthetic',
  },
  {
    id: 'w4',
    name: 'Sleek Midnight',
    price: 250.00,
    image: getImage('wig4'),
    description: 'A stunningly sleek and straight wig in a deep black. Perfect for a sophisticated look.',
    style: 'Straight',
    color: 'Black',
    length: 'Long',
    material: 'Human Hair',
  },
  {
    id: 'w5',
    name: 'Silver Pixie Dream',
    price: 130.75,
    image: getImage('wig5'),
    description: 'A modern and edgy pixie cut in a gorgeous silver-grey. Lightweight and easy to style.',
    style: 'Pixie',
    color: 'Grey',
    length: 'Short',
    material: 'Synthetic',
  },
  {
    id: 'w6',
    name: 'Pastel Candy Floss',
    price: 175.00,
    image: getImage('wig6'),
    description: 'Live your pastel dreams with this shoulder-length pastel pink wig. Soft, wavy, and romantic.',
    style: 'Wavy',
    color: 'Pastel',
    length: 'Medium',
    material: 'Synthetic',
  },
  {
    id: 'w7',
    name: 'Sunset Ombre',
    price: 280.00,
    image: getImage('wig7'),
    description: 'Long, flowing waves with a beautiful dark root to warm sunset ombre transition.',
    style: 'Wavy',
    color: 'Blonde',
    length: 'Long',
    material: 'Human Hair',
  },
  {
    id: 'w8',
    name: 'Natural Afro Crown',
    price: 199.99,
    image: getImage('wig8'),
    description: 'A full and voluminous afro-style wig that celebrates natural texture and beauty.',
    style: 'Curly',
    color: 'Black',
    length: 'Medium',
    material: 'Synthetic',
  },
  {
    id: 'w9',
    name: 'Espresso Bob',
    price: 210.00,
    image: getImage('wig9'),
    description: 'A sharp, modern bob in a deep espresso brown. Made from silky human hair.',
    style: 'Bob',
    color: 'Brunette',
    length: 'Short',
    material: 'Human Hair',
  },
  {
    id: 'w10',
    name: 'Platinum Ice Straight',
    price: 265.00,
    image: getImage('wig10'),
    description: 'Long, straight, and icy platinum blonde. A true showstopper made from premium human hair.',
    style: 'Straight',
    color: 'Blonde',
    length: 'Long',
    material: 'Human Hair',
  },
  {
    id: 'w11',
    name: 'Crimson Curls',
    price: 165.00,
    image: getImage('wig11'),
    description: 'Shoulder-length crimson red curls that are full of life and personality.',
    style: 'Curly',
    color: 'Red',
    length: 'Medium',
    material: 'Synthetic',
  },
  {
    id: 'w12',
    name: 'Ash Grey Waves',
    price: 235.00,
    image: getImage('wig12'),
    description: 'Soft, beachy waves in a trendy ash grey color. Lace front for a natural hairline.',
    style: 'Wavy',
    color: 'Grey',
    length: 'Medium',
    material: 'Human Hair',
  },
];
