import type { Wig } from './types';
import { placeholderImages } from './placeholder-images';

const getImage = (id: string) => placeholderImages.find(p => p.id === id)?.imageUrl || `https://picsum.photos/seed/${id}/600/800`;

export const products: Wig[] = [
  {
    id: 'w1',
    name: 'Ngozi',
    price: 189.99,
    image: "https://laidbyify.com/cdn/shop/files/34B90DCB-F114-469A-ACAD-7515530AE2BB.jpg?v=1756814058",
    description: 'Beautiful long, wavy blonde hair that flows naturally. Made from high-quality synthetic fibers.',
    style: 'Wavy',
    color: 'Blonde',
    length: 'Long',
    material: 'Synthetic',
  },
  {
    id: 'w2',
    name: 'Nkem (Natural Black)',
    price: 220.50,
    image: "https://laidbyify.com/cdn/shop/files/7D5C1F71-C620-45CB-95E6-A77B8EFD8E7E.jpg?v=1762186440&width=2200",
    description: 'A timeless and chic bob cut in a rich brunette shade. Made from 100% human hair.',
    style: 'Bob',
    color: 'Brunette',
    length: 'Short',
    material: 'Human Hair',
  },
  {
    id: 'w3',
    name: 'Chika',
    price: 155.00,
    image: "https://laidbyify.com/cdn/shop/files/IMG-3873.jpg?v=1760919015&width=2200",
    description: 'Make a statement with these vibrant, bouncy red curls. Fun, fearless, and fabulous.',
    style: 'Curly',
    color: 'Red',
    length: 'Medium',
    material: 'Synthetic',
  },
  {
    id: 'w4',
    name: 'Amarachi (Jet Black)',
    price: 250.00,
    image: "https://laidbyify.com/cdn/shop/files/FullSizeRender_a768257a-8218-4c15-b0fa-8fe21b490d14.jpg?v=1742301306",
    description: 'A stunningly sleek and straight wig in a deep black. Perfect for a sophisticated look.',
    style: 'Straight',
    color: 'Black',
    length: 'Long',
    material: 'Human Hair',
  },
  {
    id: 'w5',
    name: 'Silver Pixie Dream',
    price: 130.75,
    image: "https://laidbyify.com/cdn/shop/files/FullSizeRender_918ee82c-59db-4d15-9ea9-a7370ddf1267.jpg?v=1741957669",
    description: 'A modern and edgy pixie cut in a gorgeous silver-grey. Lightweight and easy to style.',
    style: 'Pixie',
    color: 'Grey',
    length: 'Short',
    material: 'Synthetic',
  },
  {
    id: 'w6',
    name: 'Pastel Candy Floss',
    price: 175.00,
    image: "https://laidbyify.com/cdn/shop/files/FullSizeRender_a768257a-8218-4c15-b0fa-8fe21b490d14.jpg?v=1742301306",
    description: 'Live your pastel dreams with this shoulder-length pastel pink wig. Soft, wavy, and romantic.',
    style: 'Wavy',
    color: 'Pastel',
    length: 'Medium',
    material: 'Synthetic',
  },
  {
    id: 'w7',
    name: 'Sunset Ombre',
    price: 280.00,
    image: "https://laidbyify.com/cdn/shop/files/FullSizeRender.jpg?v=1742299791",
    description: 'Long, flowing waves with a beautiful dark root to warm sunset ombre transition.',
    style: 'Wavy',
    color: 'Blonde',
    length: 'Long',
    material: 'Human Hair',
  },
];
